# $File: //ASP/opa/acc/eqc/saf/ludlum_m375/trunk/Ludlum_M375SimApp/src/Makefile $
# $Revision: #1 $
# $DateTime: 2019/10/24 17:42:53 $
# Last checked in by: $Author: starritt $
#

TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into
# <top>/bin/<epics_host_arch>
#
SCRIPTS += ludlum_m375_sim


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

# end
