#!/bin/bash
#
# $File: //ASP/opa/acc/eqc/saf/ludlum_m375/trunk/Ludlum_M375Sup/src/ludlum_m375_comms_reset $
# $Revision: #4 $
# $DateTime: 2020/11/13 15:16:26 $
# Last checked in by: $Author: starritt $
#
# Description:
#
#
# Copyright (c) 2020  Australian Synchrotron
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# Licence as published by the Free Software Foundation; either
# version 2.1 of the Licence, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public Licence for more details.
#
# You should have received a copy of the GNU Lesser General Public
# Licence along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Original author: Andrew Starritt
# Maintained by:   Andrew Starritt
#
# Contact details:
# as-open-source@ansto.gov.au
# 800 Blackburn Road, Clayton, Victoria 3168, Australia.
#

iam=$( basename $0 )

function terminate () {
   local arg
   for arg in "$@" ; do
      echo 1>&2 "${arg}"
   done
   exit 1
}

function usage () {
   terminate "${1}"  "" \
             "usage: ${iam:?}  PORT_NUMBER"   \
             "       ${iam:?}  --help|-h"      ""   \
             "e.g.   ${iam:?}  4011" ""
}

function help () {
   cat << HELPINFO
${iam:?} script can be used to terminate one of the ludlum_m375_c2c
client-to-client connection instances. Note: it will automatically be restarted by
the ludlum_m375_manage service if needs be.

usage: ${iam:?}  PORT_NUMBER
       ${iam:?}  --help|-h

e.g.   ${iam:?}  4011

The port number must be the port number used by the ${HOSTNAME} EPICS IOC to connect 
to the client-to-client instance. These are used as these do not change as the
actual Ludlum m375 controllers are relocated (as part of the calibration paradigm).

This script is intended to be called by the IOC via the DEVICE:COMMS_RESET_CMD
binary out (bo) records.

HELPINFO
}

if [ "${1}" == "--help" ] || [ "${1}" == "-h" ] ; then
   help
   exit 0
fi

if [ $# -lt 1 ] || [ -z "${1}" ] ; then
   usage "Null/missing parameter"
fi

# Allocate meaningfull parameter name
#
port=${1:?}

# Look for a process of the form:
# python /asp/ics/ioc/bin/linux-x86_64/ludlum_m375_c2c [options] host ${port} host 16xx
# 
pattern="python /asp/ics/ioc/bin/linux-x86_64/ludlum_m375_c2c.* host ${port} host 16[0-9][0-9]"

pid=$( ps -ef | grep -v grep | grep "${pattern:?}" | awk '{print $2}' ) 
if [ -n "${pid}" ] ; then
    # Try SIGINT first
    #
    echo "Terminating ludlum_m375_c2c pid: ${pid}"
    kill -s SIGTERM ${pid:?}

    sleep 2
    pid=$( ps -ef | grep -v grep | grep "${pattern:?}" | awk '{print $2}' ) 
    if [ -n "${pid}" ] ; then
        # That didn't work - go with SIGKILL
        #
        echo "Killing ludlum_m375_c2c pid: ${pid}"
        kill -s SIGKILL ${pid:?}
    fi
fi

# end
